version: "3"

services:
  postgresd:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - pg13:/var/lib/postgresql/data
    profiles: ["auth"]

  kratos-migrate:
    image: oryd/kratos:v0.7.1-alpha.1
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    env_file:
      - ./kratos/.env
    volumes:
      - ./kratos:/etc/config/kratos
    depends_on:
      - postgresd
    profiles: ["auth"]

  kratos:
    image: oryd/kratos:v0.7.1-alpha.1
    depends_on:
      - kratos-migrate
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    command: serve -c /etc/config/kratos/kratos.yml --dev
    env_file:
      - ./kratos/.env
    volumes:
      - ./kratos:/etc/config/kratos
    restart: unless-stopped
    profiles: ["auth"]

  oathkeeper:
    image: oryd/oathkeeper:v0.38
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper
    profiles: ["auth"]

volumes:
  pg13:
