version: "3"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - 5555:5432