version: "3"

services:
  postgresd:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - pg13:/var/lib/postgresql/data

  kratos-migrate:
    image: oryd/kratos:v0.7.1-alpha.1
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/etc/config/kratos
    depends_on:
      - postgresd

  kratos:
    image: oryd/kratos:v0.7.1-alpha.1
    depends_on:
      - kratos-migrate
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    command: serve -c /etc/config/kratos/kratos.yml --dev
    env_file:
      - .env
    volumes:
      - .:/etc/config/kratos
    restart: unless-stopped

volumes:
  pg13:
